name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        python-version: [3.10]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Node.js (for frontend)
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and build frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      # Python (for backend and AI engine)
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          pip install -r requirements.txt

      - name: Install AI engine dependencies
        working-directory: ./ai-engine
        run: |
          pip install -r requirements.txt

      # Optional: Run lint or tests (update as needed)
      - name: Lint frontend
        working-directory: ./frontend
        run: |
          npm run lint || echo "Frontend lint failed but continuing..."

      - name: Test backend
        working-directory: ./backend
        run: |
          pytest || echo "Backend tests failed but continuing..."
