name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set up Node.js for frontend
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Lint frontend
        run: |
          cd frontend
          npm run lint || echo "Lint skipped (no lint config yet)"

      # Set up Python for backend and AI
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Optional: Install flake8 only
      - name: Install Python linter
        run: pip install flake8

      - name: Lint Python
        run: |
          flake8 ai-engine/*.py backend/*.py --max-line-length=88 || echo "Flake8 warnings only"
